import json
import logging
import google.generativeai as genai
from app.core.config import settings
from app.models.schemas import SoilRequest

logger = logging.getLogger(__name__)

class SoilService:
    def __init__(self):
        try:
            print(f"DEBUG: API Key available? {'Yes' if settings.GEMINI_API_KEY else 'No'}")
            
            genai.configure(api_key=settings.GEMINI_API_KEY)
            self.model = genai.GenerativeModel("gemini-2.5-flash")
            logger.info("✓ Gemini AI Connected (Soil Service)")
        except Exception as e:
            # DEBUG LINE: Print the actual error
            print(f"CRITICAL GEMINI ERROR: {e}") 
            logger.error(f"⚠️ Gemini Init Failed: {e}")
            self.model = None

    # 🔒 HARD AGRONOMY RULE (Safety First: Do not let AI hallucinate cultivability)
    def _is_cultivable(self, ph: float) -> bool:
        return 4.0 <= ph <= 9.0

    def recommend_crop(self, request: SoilRequest):
        """
        Hybrid Rule + AI system.
        1. Cultivability is decided by strict code logic.
        2. Crop recommendations & explanations are generated by AI in the user's language.
        """
        
        # 1. Check Hard Rule
        cultivable = self._is_cultivable(request.ph)
        lang = getattr(request, 'lang', 'en')  # Default to English if missing

        # ❌ If NOT cultivable → Return immediately (Safety)
        if not cultivable:
            msg = "Land Not Cultivable (pH is outside safe range 4.0-9.0)"
            if lang == 'hi': msg = "भूमि खेती योग्य नहीं है (pH 4.0-9.0 की सुरक्षित सीमा से बाहर है)"
            if lang == 'pb': msg = "ਜ਼ਮੀਨ ਖੇਤੀ ਯੋਗ ਨਹੀਂ ਹੈ (pH 4.0-9.0 ਦੀ ਸੁਰੱਖਿਅਤ ਸੀਮਾ ਤੋਂ ਬਾਹਰ ਹੈ)"
            
            return {
                "cultivable": False,
                "message": msg,
                "explanation": "Soil pH remediation is required before cultivation.",
                "crops": []
            }

        # ⚠️ If Gemini is unavailable → Return Mock Data
        if not self.model:
            return self._get_mock_fallback(request, "Gemini API not connected", lang)

        # 2. Dynamic Language Instruction
        lang_instruction = "Answer in English."
        if lang == 'hi':
            lang_instruction = "Answer strictly in Hindi (Devanagari script). Use simple agricultural terminology."
        elif lang == 'pb':
            lang_instruction = "Answer strictly in Punjabi (Gurmukhi script). Use terms farmers understand."
        elif lang == 'gj':
            lang_instruction = "Answer strictly in Gujarati."
        elif lang == 'mr':
            lang_instruction = "Answer strictly in Marathi."
        elif lang == 'ta':
            lang_instruction = "Answer strictly in Tamil."
        elif lang == 'te':
            lang_instruction = "Answer strictly in Telugu."
        elif lang == 'bn':
            lang_instruction = "Answer strictly in Bengali."

        # 🧠 AI PROMPT
        prompt = f"""
        You are an expert Indian agronomist.
        
        CONTEXT:
        A farmer has sent soil sample data from {request.district} (India).
        The land is CONFIRMED cultivable (pH {request.ph}).
        
        SOIL DATA:
        - Nitrogen: {request.nitrogen} kg/ha
        - Phosphorus: {request.phosphorus} kg/ha
        - Potassium: {request.potassium} kg/ha
        - pH: {request.ph}
        - Rainfall: {request.rainfall} mm
        
        TASK:
        {lang_instruction}
        
        1. Provide a short "message" summarizing soil health (1 sentence).
        2. Provide a detailed "explanation" of nutrient balance.
        3. Recommend exactly 3 suitable crops.
        4. For each crop, suggest specific Urea/DAP/MOP dosage (kg/acre).
        
        OUTPUT FORMAT (Strict JSON, no markdown):
        {{
          "message": "Summary string in {lang}",
          "explanation": "Detailed explanation string in {lang}",
          "crops": [
            {{
              "crop": "Crop Name in {lang}",
              "confidence": "High / Medium",
              "urea_dose": "Value",
              "dap_dose": "Value",
              "mop_dose": "Value",
              "reason": "Why this crop fits (in {lang})"
            }}
          ]
        }}
        """

        try:
            # Generate Content
            response = self.model.generate_content(prompt)
            
            # Clean response (remove markdown code blocks if AI adds them)
            clean_text = response.text.replace("```json", "").replace("```", "").strip()
            
            data = json.loads(clean_text)

            # Return structured data
            return {
                "cultivable": True,
                "message": data.get("message", "Analysis Complete"),
                "explanation": data.get("explanation", ""),
                "crops": data.get("crops", [])
            }

        except Exception as e:
            logger.error(f"Gemini Analysis Error: {e}")
            logger.info("⚠️ Switching to Mock Data for resilience.")
            return self._get_mock_fallback(request, str(e), lang)

    def _get_mock_fallback(self, request: SoilRequest, error_msg="Unknown Error", lang="en"):
        """
        Generates realistic fake data if the AI fails, roughly translated.
        """
        msg = f"AI Offline (System Error: {error_msg})"
        expl = "Using historical data for your district due to connection failure."
        
        # Simple hardcoded translations for the Fallback Message
        if lang == 'hi':
            msg = "सिस्टम ऑफ़लाइन (कनेक्शन त्रुटि)"
            expl = "कनेक्शन विफलता के कारण आपके जिले के ऐतिहासिक डेटा का उपयोग किया जा रहा है।"
        elif lang == 'pb':
            msg = "ਸਿਸਟਮ ਔਫਲਾਈਨ (ਕਨੈਕਸ਼ਨ ਗਲਤੀ)"
            expl = "ਕਨੈਕਸ਼ਨ ਫੇਲ ਹੋਣ ਕਾਰਨ ਤੁਹਾਡੇ ਜ਼ਿਲ੍ਹੇ ਦੇ ਪੁਰਾਣੇ ਡੇਟਾ ਦੀ ਵਰਤੋਂ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ।"

        return {
            "cultivable": True,
            "message": msg,
            "explanation": expl,
            "crops": [
                {
                    "crop": "Wheat (Simulated)",
                    "confidence": "High",
                    "urea_dose": "45",
                    "dap_dose": "25",
                    "mop_dose": "10",
                    "reason": "Standard fallback recommendation."
                },
                {
                    "crop": "Rice (Simulated)",
                    "confidence": "Medium",
                    "urea_dose": "60",
                    "dap_dose": "30",
                    "mop_dose": "20",
                    "reason": "Standard fallback recommendation."
                }
            ]
        }