from pydantic import BaseModel, Field, validator, ConfigDict
from typing import Optional, List
from datetime import date

# -------------------------
# COMMON / BASE SCHEMAS
# -------------------------
class MessageResponse(BaseModel):
    message: str


# -------------------------
# AUTH / FARMER SCHEMAS
# ========================

class FarmerRegister(BaseModel):
    """
    Farmer registration request.
    Client sends these fields - farmer_id is auto-generated by server.
    """
    name: str = Field(..., min_length=1, example="Ramesh Kumar")
    phone: str = Field(..., pattern=r"^\d{10}$", example="9876543210")
    state: str = Field(..., example="Maharashtra")
    district: str = Field(..., example="Pune")
    language: str = Field(default="en", example="en")
    
    @validator('name')
    def name_no_numbers(cls, v):
        if any(char.isdigit() for char in v):
            raise ValueError('Name cannot contain numbers')
        return v.strip()


class FarmerResponse(BaseModel):
    """
    Farmer profile response.
    Includes the auto-generated farmer_id.
    """
    farmer_id: str = Field(..., example="FARM_9876543210_a1b2c3d4")
    name: str = Field(..., example="Ramesh Kumar")
    phone: str = Field(..., example="9876543210")
    state: str = Field(..., example="Maharashtra")
    district: str = Field(..., example="Pune")
    language: Optional[str] = Field(default="en", example="en")
    
    model_config = ConfigDict(from_attributes=True)


class LoginRequest(BaseModel):
    phone: str = Field(..., pattern=r"^\d{10}$")


class OTPVerify(BaseModel):
    phone: str = Field(..., pattern=r"^\d{10}$")
    otp: str = Field(..., min_length=4, max_length=6)


# -------------------------
# SOIL SCHEMAS
# -------------------------
class SoilRequest(BaseModel):
    district: str = Field(..., example="Pune")
    nitrogen: float = Field(..., ge=0, example=45.0)
    phosphorus: float = Field(..., ge=0, example=30.0)
    potassium: float = Field(..., ge=0, example=40.0)
    ph: float = Field(..., ge=0, le=14, example=6.5)
    rainfall: float = Field(..., ge=0, example=120.0)
    language: str = Field(default="en")


class SoilPredictionResponse(BaseModel):
    recommended_crop: str = Field(..., example="Wheat")
    confidence: Optional[float] = Field(None, ge=0, le=1, example=0.87)
    explanation: Optional[str] = None


# -------------------------
# MARKET SCHEMAS
# -------------------------
class MarketQuery(BaseModel):
    crop_name: str = Field(..., example="Rice")
    state: Optional[str] = Field(None, example="Punjab")
    language: str = Field(default="en")


class MarketPriceResponse(BaseModel):
    crop_name: str
    state: str
    average_price: float
    last_updated: date


class MarketHistoryItem(BaseModel):
    date: date
    price: float


class MarketHistoryResponse(BaseModel):
    crop_name: str
    state: str
    history: List[MarketHistoryItem]


# -------------------------
# CREDIT / LOAN SCHEMAS
# -------------------------
class CreditRequest(BaseModel):
    farmer_id: str
    land_area_acres: float = Field(..., gt=0, example=2.5)
    crop_name: str = Field(..., example="Wheat")
    expected_yield_quintal: float = Field(..., gt=0, example=25)


class CreditResponse(BaseModel):
    eligible_amount: float
    interest_rate: float
    repayment_period_months: int
    eligibility_status: str = Field(..., example="eligible")


# -------------------------
# LOCATION SCHEMAS
# -------------------------
class Location(BaseModel):
    lat: float = Field(..., ge=-90, le=90)
    lng: float = Field(..., ge=-180, le=180)
    district: Optional[str] = None